name: "Continuous Integration"

on:
  pull_request:
    branches:
      - "*.x"
    paths:
      - .github/workflows/continuous-integration.yml
      - ci/**
      - composer.*
      - src/**
      - tests/**
  push:
    paths:
      - .github/workflows/continuous-integration.yml
      - ci/**
      - composer.*
      - src/**
      - tests/**

env:
  fail-fast: true

jobs:
  phpunit-smoke-check:
    name: "PHPUnit with SQLite"
    runs-on: "ubuntu-22.04"

    strategy:
      matrix:
        deps:
          - "highest"
        include:
          - php-version: "8.2"
            dbal-version: "4@dev"
            extension: "pdo_sqlite"
          - php-version: "8.2"
            dbal-version: "4@dev"
            extension: "sqlite3"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: "apcu, pdo, ${{ matrix.extension }}"
          ini-values: "zend.assertions=1, apc.enable_cli=1"

      - name: "Require specific DBAL version"
        run: "composer require doctrine/dbal ^${{ matrix.dbal-version }} --no-update"
        if: "${{ matrix.dbal-version != 'default' }}"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v3"
        with:
          composer-options: "--ignore-platform-req=php+"
          dependency-versions: "${{ matrix.deps }}"

      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit -c ci/github/phpunit/${{ matrix.extension }}.xml"
        env:
            ENABLE_SECOND_LEVEL_CACHE: 0

      - name: "Run PHPUnit with Second Level Cache"
        run: "vendor/bin/phpunit -c ci/github/phpunit/${{ matrix.extension }}.xml --exclude-group performance,non-cacheable,locking_functional"
        env:
            ENABLE_SECOND_LEVEL_CACHE: 1


  phpunit-postgres:
    name: "PHPUnit with PostgreSQL"
    runs-on: "ubuntu-22.04"
    needs: "phpunit-smoke-check"

    strategy:
      matrix:
        include:
          - php-version: "8.2"
            dbal-version: "4@dev"
            postgres-version: "14"
            extension: pdo_pgsql

    services:
      postgres:
        image: "postgres:${{ matrix.postgres-version }}"
        env:
          POSTGRES_PASSWORD: "postgres"

        options: >-
          --health-cmd "pg_isready"

        ports:
          - "5432:5432"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: "pgsql pdo_pgsql"
          ini-values: "zend.assertions=1, apc.enable_cli=1"

      - name: "Require specific DBAL version"
        run: "composer require doctrine/dbal ^${{ matrix.dbal-version }} --no-update"
        if: "${{ matrix.dbal-version != 'default' }}"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v3"
        with:
          composer-options: "--ignore-platform-req=php+"

      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit -c ci/github/phpunit/pdo_pgsql.xml"


  phpunit-mariadb:
    name: "PHPUnit with MariaDB"
    runs-on: "ubuntu-22.04"
    needs: "phpunit-smoke-check"

    strategy:
      matrix:
        php-version:
          - "8.3"
          - "8.4"
        dbal-version:
          - "4@dev"
        mariadb-version:
          - "11.4"
        extension:
          - "mysqli"
          - "pdo_mysql"

    services:
      mariadb:
        image: "mariadb:${{ matrix.mariadb-version }}"
        env:
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
          MARIADB_DATABASE: "doctrine_tests"

        options: >-
          --health-cmd "healthcheck.sh --connect --innodb_initialized"

        ports:
          - "3306:3306"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 2

      - name: "Require specific DBAL version"
        run: "composer require doctrine/dbal ^${{ matrix.dbal-version }} --no-update"
        if: "${{ matrix.dbal-version != 'default' }}"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          ini-values: "zend.assertions=1, apc.enable_cli=1"
          extensions: "${{ matrix.extension }}"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v3"
        with:
          composer-options: "--ignore-platform-req=php+"

      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit -c ci/github/phpunit/${{ matrix.extension }}.xml"


  phpunit-mysql:
    name: "PHPUnit with MySQL"
    runs-on: "ubuntu-22.04"
    needs: "phpunit-smoke-check"

    strategy:
      matrix:
        include:
          - php-version: "8.2"
            dbal-version: "4@dev"
            mysql-version: "8.0"
            extension: "mysqli"
          - php-version: "8.2"
            dbal-version: "4@dev"
            mysql-version: "8.0"
            extension: "pdo_mysql"

    services:
      mysql:
        image: "mysql:${{ matrix.mysql-version }}"

        options: >-
          --health-cmd "mysqladmin ping --silent"
          -e MYSQL_ALLOW_EMPTY_PASSWORD=yes
          -e MYSQL_DATABASE=doctrine_tests

        ports:
          - "3306:3306"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          ini-values: "zend.assertions=1, apc.enable_cli=1"
          extensions: "${{ matrix.extension }}"

      - name: "Require specific DBAL version"
        run: "composer require doctrine/dbal ^${{ matrix.dbal-version }} --no-update"
        if: "${{ matrix.dbal-version != 'default' }}"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v3"
        with:
          composer-options: "--ignore-platform-req=php+"

      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit -c ci/github/phpunit/${{ matrix.extension }}.xml"
        env:
            ENABLE_SECOND_LEVEL_CACHE: 0

      - name: "Run PHPUnit with Second Level Cache"
        run: "vendor/bin/phpunit -c ci/github/phpunit/${{ matrix.extension }}.xml --exclude-group performance,non-cacheable,locking_functional"
        env:
            ENABLE_SECOND_LEVEL_CACHE: 1
